#Admin
#These routes are prefix with /admin/cms-pages in routing.yml
nfq_cmspage_list:
    path: /
    methods: [ "GET" ]
    controller: NfqCmsPageBundle:Admin/CmsPage:index

nfq_cmspage_new:
    path: /new
    methods: [ "GET" ]
    controller: NfqCmsPageBundle:Admin/CmsPage:new

nfq_cmspage_create:
    path: /new
    methods: [ "POST" ]
    controller: NfqCmsPageBundle:Admin/CmsPage:create

nfq_cmspage_update:
    path: /{id}/update
    methods: [ "GET", "POST" ]
    controller: NfqCmsPageBundle:Admin/CmsPage:update

nfq_cmspage_delete:
    path: /{id}/delete
    methods: [ "GET", "POST" ]
    controller: NfqCmsPageBundle:Admin\CmsPage:delete
